### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Zerg00s** [koltyakov/generator-sppp#4] opened 2016-11-07 01:53 UTC
There were a few modules I had to manually install after running generator-sppp 1.5:
npm install request-promise --save
npm install node-sp-auth --save
npm install socket.io-client --save

**Comment by koltyakov** [comment] 2016-11-07 05:19
Hi,

It's the dependencies from sp-live-reload and should be installed automatically.

Could you please describe the scenario, when these references were missed? Was it an update?

**Comment by Zerg00s** [comment] 2016-11-07 22:42
Maybe I did something wrong but these were the steps I've followed:
- yo ( update generator-sppp)
- yo (generate a new project from scratch in a new empty folder)
- yeoman says that it will do "npm install" automatically and it does so. 
- when trying to use gulp tasks that rely on sp-live-reload, I get errors about these three modules being missing

**Comment by koltyakov** [comment] 2016-11-08 06:40
Was not able to reproduce on a couple different workstations.
Is it still happening on your end?
It will be incorrect to include these dependencies in the package.
If you face such a behavior could you please provide some additional information:
- node/npm/yo versions
- zipped node_modules folder from early created project from scratch (or a complete project arch)

**Closed** 2016-11-22 07:18 UTC
